# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main1.o main2.o main3.o main4.o main5.o main6.o main7.o main8.o main9.o main10.o main13.o
LINKOBJ  = main1.o main2.o main3.o main4.o main5.o main6.o main7.o main8.o main9.o main10.o main13.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = middle.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main1.o: main1.cpp
	$(CPP) -c main1.cpp -o main1.o $(CXXFLAGS)

main2.o: main2.cpp
	$(CPP) -c main2.cpp -o main2.o $(CXXFLAGS)

main3.o: main3.cpp
	$(CPP) -c main3.cpp -o main3.o $(CXXFLAGS)

main4.o: main4.cpp
	$(CPP) -c main4.cpp -o main4.o $(CXXFLAGS)

main5.o: main5.cpp
	$(CPP) -c main5.cpp -o main5.o $(CXXFLAGS)

main6.o: main6.cpp
	$(CPP) -c main6.cpp -o main6.o $(CXXFLAGS)

main7.o: main7.cpp
	$(CPP) -c main7.cpp -o main7.o $(CXXFLAGS)

main8.o: main8.cpp
	$(CPP) -c main8.cpp -o main8.o $(CXXFLAGS)

main9.o: main9.cpp
	$(CPP) -c main9.cpp -o main9.o $(CXXFLAGS)

main10.o: main10.cpp
	$(CPP) -c main10.cpp -o main10.o $(CXXFLAGS)

main13.o: main13.cpp
	$(CPP) -c main13.cpp -o main13.o $(CXXFLAGS)
